<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;

class UserRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;//no need authenticate to use this one
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
	        'email'         => 'required|email|max:255|unique:users',
	        'password'      => 'required|min:6',
	        'avatar'        => 'mimes:jpeg,png',
	        'first_name'    => 'required|max:255',
	        'last_name'     => 'required|max:255',
	        'phone_number'  => 'max:20|min:6',
	        'is_private'    => 'integer|in:0,1',
	        'is_enable_all_zpot'=> 'integer|in:0,1',
	        'lat'           => 'float',
	        'long'          => 'float',
	        'birthday'      => 'date|date_format:d-m-Y',
	        'gender'        => 'required|integer|in:0,1,2',
        ];
    }

	/**
	 * Set custom attributes for validator errors.
	 *
	 * @return array
	 */
	public function attributes()
	{
		return parent::attributes(); // TODO: Change the autogenerated stub
	}
}
